<?xml version="1.0" encoding="utf-8"?><Database Name="SAM" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-HBDOSNK\SQLEXPRESS;Initial Catalog=SAM;Integrated Security=True" SettingsObjectName="StudentAttendanceSystem.Properties.Settings" SettingsPropertyName="SAMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Attendance" Member="Attendances">
    <Type Name="Attendance">
      <Column Name="TeacherID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CourseID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StudentHours" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LatestDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Course_Attendance" Member="Course" ThisKey="CourseID" OtherKey="id" Type="Course" IsForeignKey="true" />
      <Association Name="Teacher_Attendance" Member="Teacher" ThisKey="TeacherID" OtherKey="id" Type="Teacher" IsForeignKey="true" />
      <Association Name="Student_Attendance" Member="Student" ThisKey="StudentID" OtherKey="id" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Course" Member="Courses">
    <Type Name="Course">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CourseName" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Hours" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoursPerSession" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContactHours" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Section" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Course_Attendance" Member="Attendances" ThisKey="id" OtherKey="CourseID" Type="Attendance" />
    </Type>
  </Table>
  <Table Name="dbo.Teacher" Member="Teachers">
    <Type Name="Teacher">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Teacher_Attendance" Member="Attendances" ThisKey="id" OtherKey="TeacherID" Type="Attendance" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Student_Attendance" Member="Attendances" ThisKey="id" OtherKey="StudentID" Type="Attendance" />
    </Type>
  </Table>
</Database>